name: Build

on: workflow_dispatch

jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Dependencies
      run: |
        go mod download
        go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Desktop Builds
      run: |
        mkdir builds && chmod 777 builds
        GOOS=linux GOARCH=amd64 go build -o builds/ShareiT-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o builds/ShareiT-linux-arm64
        GOOS=darwin GOARCH=amd64 go build -o builds/ShareiT-macos-amd64
        GOOS=windows GOARCH=amd64 go build -o builds/ShareiT-windows-amd64.exe

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r19c

    - name: Mobile Builds
      run: |
        fyne package --appVersion 0.0.1 --appID net.anjanamadu.shareit --name ShareiT --os android --release true && mv ShareiT.apk builds/ShareiT-android-universal.apk
        fyne package --appVersion 0.0.1 --appID net.anjanamadu.shareit --name ShareiT --os android/arm --release true && mv ShareiT.apk builds/ShareiT-android-arm.apk
        fyne package --appVersion 0.0.1 --appID net.anjanamadu.shareit --name ShareiT --os android/arm64 --release true && mv ShareiT.apk builds/ShareiT-android-arm64.apk
        fyne package --appVersion 0.0.1 --appID net.anjanamadu.shareit --name ShareiT --os android/amd64 --release true && mv ShareiT.apk builds/ShareiT-android-amd64.apk
        fyne package --appVersion 0.0.1 --appID net.anjanamadu.shareit --name ShareiT --os ios --release true && mv ShareiT.ipa builds/ShareiT-ios-universal.ipa

    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifact: builds/*
        body: "Builds for ShareiT."
        name: "Builds"